---
galaxy_info:
  author: Lowess
  role_name: harvest
  description: Install and configure Harvest from GitHub release artifacts.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - harvest
    - raspberrypi
    - automation
    - api

dependencies:
  - common
